<?php

namespace App\Model;

class PartyManager extends AbstractManager
{
    public const TABLE = 'event';

    public function selectAllParty(int $userId): ?array
    {
        $statement = $this->pdo->prepare("SELECT * FROM " . static::TABLE . " WHERE user_id=:user_id");
        $statement->bindValue('user_id', $userId);
        $statement->execute();

        return $statement->fetchAll() ?: null;
    }

    public function selectOneById(int $id): array|false
    {
        return parent::selectOneById($id); // TODO: Change the autogenerated stub
    }
}
